apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        # Tokenless authentication: Uses IAM Role via Service Account (IRSA) or Pod Identity
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-runtime-secrets
  namespace: prod-workload
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: app-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: cloud-devsecops/lab/app-secrets
        property: DATABASE_PASSWORD
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: cloud-devsecops/lab/app-secrets
        property: JWT_SECRET_KEY
